create table tb_filme(
    id number generated by default as identity,
    titulo varchar2(100),
    data_lancamento date,
    diretor varchar2(80),
    atores varchar2(200),
    nota number(2, 1),
    sinopse varchar2(400),
    estudio varchar2(100),
    primary key(id)
);