create table tbr_enquete(
    id number generated by default as identity,
    nome varchar2(100),
    categoria varchar2(100),
    primary key(id)
);

create table tbr_pergunta(
    id number generated by default as identity,
    texto varchar2(300),
    tipo number(1),
    numero number(2),
    id_enquete number,
    primary key(id),
    foreign key(id_enquete) references tbr_enquete(id)
);

create table tbr_opcoes(
    alternativa varchar2(100),
    rotulo number(2),
    id_pergunta number,
    foreign key(id_pergunta) references tbr_pergunta(id)
);

create table tbr_pessoa(
    id number generated by default as identity,
    nome varchar2(100),
    idade number(2),
    sexo varchar2(20),
    municipio varchar2(50),
    escolaridade varchar2(50),
    primary key(id)
);

create table tbr_resposta(
    texto varchar2(300),
    datahora timestamp,
    id_pessoa number,
    id_pergunta number,
    foreign key(id_pessoa) references tbr_pessoa(id),
    foreign key(id_pergunta) references tbr_pergunta(id)
);











